# Site settings
title: My Jekyll Site
description: A site using GitHub Pages and a custom domain

# URL settings
url: "https://www.cappel.li"  
baseurl: "" 

# Permalink settings for clean URLs
permalink: /:title/  

# Jekyll settings
markdown: kramdown

# Optional: Enable RSS feed generation for blogs
feed:
  path: feed.xml

# Collections to include custom pages (index folder)
collections:
  HTML:
    output: true

# Custom domain and SSL settings
github:
  url: "https://www.cappel.li"
  ssl: true
